# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Display = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Display.setGeometry(QtCore.QRect(670, 70, 371, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.lbl_Display.setFont(font)
        self.lbl_Display.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_Display.setObjectName("lbl_Display")
        self.btn_Change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Change.setGeometry(QtCore.QRect(330, 90, 291, 91))
        self.btn_Change.setObjectName("btn_Change")
        self.line_Input = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Input.setGeometry(QtCore.QRect(80, 100, 211, 71))
        self.line_Input.setObjectName("line_Input")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 240, 211, 151))
        self.textEdit.setObjectName("textEdit")
        self.lbl_TextEdit = QtWidgets.QLabel(self.centralwidget)
        self.lbl_TextEdit.setGeometry(QtCore.QRect(330, 240, 271, 141))
        self.lbl_TextEdit.setObjectName("lbl_TextEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(80, 420, 211, 111))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lbl_PlainEdit = QtWidgets.QLabel(self.centralwidget)
        self.lbl_PlainEdit.setGeometry(QtCore.QRect(340, 430, 231, 81))
        self.lbl_PlainEdit.setObjectName("lbl_PlainEdit")
        self.btn_ClearLblPlain = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ClearLblPlain.setGeometry(QtCore.QRect(670, 420, 191, 91))
        self.btn_ClearLblPlain.setObjectName("btn_ClearLblPlain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Display.setText(_translate("MainWindow", "TextLabel"))
        self.btn_Change.setText(_translate("MainWindow", "PushButton"))
        self.lbl_TextEdit.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_PlainEdit.setText(_translate("MainWindow", "TextLabel"))
        self.btn_ClearLblPlain.setText(_translate("MainWindow", "Clear Plain Label"))
