# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Display = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Display.setGeometry(QtCore.QRect(220, 280, 371, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.lbl_Display.setFont(font)
        self.lbl_Display.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lbl_Display.setObjectName("lbl_Display")
        self.btn_Change = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Change.setGeometry(QtCore.QRect(450, 130, 291, 91))
        self.btn_Change.setObjectName("btn_Change")
        self.line_Input = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Input.setGeometry(QtCore.QRect(160, 140, 211, 71))
        self.line_Input.setObjectName("line_Input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Display.setText(_translate("MainWindow", "TextLabel"))
        self.btn_Change.setText(_translate("MainWindow", "PushButton"))
