# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenFile.setGeometry(QtCore.QRect(160, 130, 75, 23))
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.btnOpenFolder = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenFolder.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.btnOpenFolder.setObjectName("btnOpenFolder")
        self.lblShowFilePath = QtWidgets.QTextEdit(self.centralwidget)
        self.lblShowFilePath.setGeometry(QtCore.QRect(330, 100, 104, 71))
        self.lblShowFilePath.setObjectName("lblShowFilePath")
        self.lblShowFolderPath = QtWidgets.QTextEdit(self.centralwidget)
        self.lblShowFolderPath.setGeometry(QtCore.QRect(330, 250, 104, 71))
        self.lblShowFolderPath.setObjectName("lblShowFolderPath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOpenFile.setText(_translate("MainWindow", "Open File"))
        self.btnOpenFolder.setText(_translate("MainWindow", "Open Folder"))
