# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_Grid = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_Grid.setGeometry(QtCore.QRect(40, 350, 131, 19))
        self.checkBox_Grid.setObjectName("checkBox_Grid")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 390, 471, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_x = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.horizontalLayout.addWidget(self.lineEdit_x)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_cdfx = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEdit_cdfx.setObjectName("lineEdit_cdfx")
        self.horizontalLayout.addWidget(self.lineEdit_cdfx)
        self.pdfcdf = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pdfcdf.setObjectName("pdfcdf")
        self.horizontalLayout.addWidget(self.pdfcdf)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 440, 331, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.hSlider_x = QtWidgets.QSlider(parent=self.horizontalLayoutWidget_2)
        self.hSlider_x.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.hSlider_x.setObjectName("hSlider_x")
        self.horizontalLayout_2.addWidget(self.hSlider_x)
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.graphWidget = PlotWidget(parent=self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(40, 30, 471, 311))
        self.graphWidget.setObjectName("graphWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_Grid.setText(_translate("MainWindow", "Grid ON / OFF"))
        self.label.setText(_translate("MainWindow", "x = "))
        self.label_2.setText(_translate("MainWindow", "CDF(x) = "))
        self.pdfcdf.setText(_translate("MainWindow", "PDF/CDF"))
        self.label_3.setText(_translate("MainWindow", "-s"))
        self.label_4.setText(_translate("MainWindow", "s"))
from pyqtgraph import PlotWidget
