# Form implementation generated from reading ui file 'd:\software\PyQT-Practice\leture8 progress bar\main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 151)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.barProgress = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.barProgress.setGeometry(QtCore.QRect(70, 50, 118, 23))
        self.barProgress.setProperty("value", 24)
        self.barProgress.setObjectName("barProgress")
        self.btnGo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGo.setGeometry(QtCore.QRect(300, 50, 75, 23))
        self.btnGo.setObjectName("btnGo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGo.setText(_translate("MainWindow", "Go"))
